stages:
  - compile
  - build
  - deploy

variables:
  DOMAIN_NAME: wingecosys.com
  SERVICE_NAME: "$CI_PROJECT_NAME"
  DOCKER_REGISTRY: "$AWS_ECR"
  SERVER_PORT: "8080"
  SUB_DOMAIN_NAME: "${CI_COMMIT_REF_NAME}-${CI_PROJECT_NAME}"
#  KUBE_LOAD_CONFIG_FILE: $HOME/.kube/config

build-jar:
  stage: compile
  image: gradle:jdk8
  only:
    - dev
  script:
    - gradle bootjar -x test
    - rm -f build/libs/*-plain.jar
    - mv build/libs/$(ls build/libs) app.jar
  artifacts:
    paths:
      - app.jar

docker-build:
  stage: build
  image:
    name: public.ecr.aws/b1t9u1a9/awscli:0.0.1
  before_script:
    - VERSION=$(cat version.properties || echo '0.0.1' | sed 's/.*VERSION=//')
    - IMAGE_TAG=$VERSION-$CI_COMMIT_SHORT_SHA
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_REF_NAME.${IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_REF_NAME.${IMAGE_TAG}
  only:
    - dev

include: '/.gitlab/deployment.yml'