configmap:
  stage: env_var
  image:
    name: public.ecr.aws/b1t9u1a9/kubectl:0.0.1
  before_script:
    - mkdir -p $HOME/.kube && rm -f $HOME/.kube/config && cp $KUBE_CONFIG_FILE $HOME/.kube/config
  script:
    - |
      cat <<EOF | kubectl apply -n logging -f -
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: http-echo-configmap 
      data:
        MESSAGE: $HTTP_ECHO_MESSAGE
      EOF
  only:
    - dev