deploy:
  stage: deploy
  image: public.ecr.aws/b1t9u1a9/spring-boot:0.0.9
  before_script:
    - mkdir -p $HOME/.kube && rm -f $HOME/.kube/config && cp $KUBE_CONFIG_FILE $HOME/.kube/config
    - VERSION=$(cat version.properties || echo '0.0.1' | sed 's/.*VERSION=//')
    - IMAGE_TAG=$VERSION-$CI_COMMIT_SHORT_SHA
  environment:
    name: "${CI_COMMIT_REF_NAME}"
    url: "https://${CI_COMMIT_REF_NAME}-${CI_PROJECT_NAME}.wingecosys.com"
  script:
    - |
      cat <<EOF > /spring-boot/resources/configmap.yaml
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: ${SERVICE_NAME}-configmap
      data:
        MESSAGE: $HTTP_ECHO_MESSAGE
      EOF

    - |
      cat <<EOF > /spring-boot/resources/deployment.yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${SERVICE_NAME}
        labels:
          app: ${SERVICE_NAME}
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ${SERVICE_NAME}
        template:
          metadata:
            labels:
              app: ${SERVICE_NAME}
          spec:
            containers:
              - name: ${SERVICE_NAME}
                image: $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_REF_NAME.${IMAGE_TAG}
                ports:
                  - containerPort: 8080
                envFrom:
                  - configMapRef:
                      name: ${SERVICE_NAME}-configmap
      EOF
    - |
      cat <<EOF > /spring-boot/resources/service.yaml
      apiVersion: v1
      kind: Service
      metadata:
        name: ${SERVICE_NAME}
        labels:
          app: ${SERVICE_NAME}
      spec:
        selector:
          app: ${SERVICE_NAME}
        type: ClusterIP
        ports:
          - protocol: TCP
            port: ${SERVER_PORT}
            targetPort: ${SERVER_PORT}
      EOF
    - ls -la /spring-boot/resources
    - cd /spring-boot
    - terraform init
      -backend-config="address=https://gitlab.wingmarts.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${SUB_DOMAIN_NAME}"
      -backend-config="lock_address=https://gitlab.wingmarts.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${SUB_DOMAIN_NAME}/lock"
      -backend-config="unlock_address=https://gitlab.wingmarts.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${SUB_DOMAIN_NAME}/lock"
      -backend-config="username=gitlab-ci-token"
      -backend-config="password=${CI_JOB_TOKEN}"
      -backend-config="lock_method=POST"
      -backend-config="unlock_method=DELETE"
      -backend-config="retry_wait_min=5"
    - terraform apply --auto-approve
      -var "sub_domain=${SUB_DOMAIN_NAME}"
      -var "cloudflare_zone_id=${CLOUDFLARE_ZONE_ID}"
      -var "kube_master_ip=${KUBE_MASTER_IP}"
      -var 'kube_files=["/spring-boot/resources/configmap.yaml","/spring-boot/resources/deployment.yaml","/spring-boot/resources/service.yaml"]'
  only:
    - dev